"""Initial migration

Revision ID: d22eb937f665
Revises: 
Create Date: 2025-06-12 17:20:34.157954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22eb937f665'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('min_item_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raids_id'), 'raids', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('server', sa.String(length=50), nullable=False),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slot', sa.Enum('WEAPON', 'HEAD', 'BODY', 'HANDS', 'LEGS', 'FEET', 'EARRINGS', 'NECKLACE', 'BRACELET', 'RING', name='equipmentslot'), nullable=False),
    sa.Column('equipment_type', sa.Enum('RAID_HERO', 'RAID_NORMAL', 'TOME', 'TOME_AUGMENTED', 'CRAFTED', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('item_level', sa.Integer(), nullable=False),
    sa.Column('job_category', sa.String(length=100), nullable=True),
    sa.Column('raid_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('tome_cost', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('raid_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('distribution_method', sa.Enum('PRIORITY', 'FIRST_COME', name='distributionmethod'), nullable=True),
    sa.Column('target_item_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_recruiting', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_groups_id'), 'raid_groups', ['id'], unique=False)
    op.create_table('equipment_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('is_starting_set', sa.Boolean(), nullable=True),
    sa.Column('is_bis_set', sa.Boolean(), nullable=True),
    sa.Column('is_current_set', sa.Boolean(), nullable=True),
    sa.Column('total_item_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_sets_id'), 'equipment_sets', ['id'], unique=False)
    op.create_table('item_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.Enum('EQUIPMENT_COFFER', 'WEAPON_COFFER', 'UPGRADE_ITEM', 'TOME_MATERIAL', 'TOKEN', 'WEAPON_TOKEN', 'MOUNT', 'OTHER', name='itemtype'), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('priority_order', sa.JSON(), nullable=True),
    sa.Column('completed_users', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_distributions_id'), 'item_distributions', ['id'], unique=False)
    op.create_table('raid_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('can_manage_schedule', sa.Boolean(), nullable=True),
    sa.Column('can_manage_distribution', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_members_id'), 'raid_members', ['id'], unique=False)
    op.create_table('raid_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('target_floors', sa.String(length=50), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('minimum_members', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_schedules_id'), 'raid_schedules', ['id'], unique=False)
    op.create_table('resource_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('required_resources', sa.JSON(), nullable=True),
    sa.Column('obtained_resources', sa.JSON(), nullable=True),
    sa.Column('remaining_resources', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_requirements_id'), 'resource_requirements', ['id'], unique=False)
    op.create_table('distribution_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.Enum('EQUIPMENT_COFFER', 'WEAPON_COFFER', 'UPGRADE_ITEM', 'TOME_MATERIAL', 'TOKEN', 'WEAPON_TOKEN', 'MOUNT', 'OTHER', name='itemtype'), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['item_distributions.id'], ),
    sa.ForeignKeyConstraint(['raid_group_id'], ['raid_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_histories_id'), 'distribution_histories', ['id'], unique=False)
    op.create_table('equipment_set_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_set_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Enum('WEAPON', 'HEAD', 'BODY', 'HANDS', 'LEGS', 'FEET', 'EARRINGS', 'NECKLACE', 'BRACELET', 'RING', name='equipmentslot'), nullable=False),
    sa.Column('is_obtained', sa.Boolean(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['equipment_set_id'], ['equipment_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_set_items_id'), 'equipment_set_items', ['id'], unique=False)
    op.create_table('raid_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actually_attended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['raid_schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_attendances_id'), 'raid_attendances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_attendances_id'), table_name='raid_attendances')
    op.drop_table('raid_attendances')
    op.drop_index(op.f('ix_equipment_set_items_id'), table_name='equipment_set_items')
    op.drop_table('equipment_set_items')
    op.drop_index(op.f('ix_distribution_histories_id'), table_name='distribution_histories')
    op.drop_table('distribution_histories')
    op.drop_index(op.f('ix_resource_requirements_id'), table_name='resource_requirements')
    op.drop_table('resource_requirements')
    op.drop_index(op.f('ix_raid_schedules_id'), table_name='raid_schedules')
    op.drop_table('raid_schedules')
    op.drop_index(op.f('ix_raid_members_id'), table_name='raid_members')
    op.drop_table('raid_members')
    op.drop_index(op.f('ix_item_distributions_id'), table_name='item_distributions')
    op.drop_table('item_distributions')
    op.drop_index(op.f('ix_equipment_sets_id'), table_name='equipment_sets')
    op.drop_table('equipment_sets')
    op.drop_index(op.f('ix_raid_groups_id'), table_name='raid_groups')
    op.drop_table('raid_groups')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_raids_id'), table_name='raids')
    op.drop_table('raids')
    # ### end Alembic commands ###
